version: '3'
services:
  nginx:
    container_name: ai-debug-nginx
    image: nginx
    ports:
      - "8007:80"
    volumes:
      - "${GOPATH}${HUB_SCRIPTS_PATH}:${NGINX_HTML_DIR}/hub"
      - "./agent-binaries:${NGINX_HTML_DIR}/dist"
  ngrok_install_server:
    image: shkoliar/ngrok:latest
    container_name: ai-local-install-server
    ports:
      - 4551:4551
    environment:
      - AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - DOMAIN=host.docker.internal
      - SUBDOMAIN=ai-local-install
      - PORT=8007
  ngrok_hub_controller:
    image: shkoliar/ngrok:latest
    container_name: ai-local-hub-controller
    ports:
      - 4552:4551
    environment:
      - AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - DOMAIN=host.docker.internal
      - SUBDOMAIN=ai-local-hub
      - PORT=9001
