version: '3'
services:
  aiw-debug-nginx:
    container_name: aiw-debug-server
    image: nginx
    ports:
      - "8007:80"
    volumes:
      - "${GOPATH}${HUB_SCRIPTS_PATH}:${NGINX_HTML_DIR}/hub"
      - "./agent-binaries:${NGINX_HTML_DIR}/dist"
  file-server:
    image: shkoliar/ngrok:latest
    container_name: installation-script-and-agent-binary-server
    ports:
      - 4551:4551
    environment:
      - AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - DOMAIN=host.docker.internal
      - SUBDOMAIN=${FILE_SERVER_SUB_DOMAIN}${SESSION_NAME:?set session name in .env file}
      - PORT=8007
  hub-server:
    image: shkoliar/ngrok:latest
    container_name: hub-server
    ports:
      - 4552:4551
    environment:
      - AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - DOMAIN=host.docker.internal
      - SUBDOMAIN=${HUB_SERVER_SUBDOMAIN}${SESSION_NAME:?set session name in .env file}
      - PORT=9001
